### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by willfu** [Xinering/cocoapi#1]
After I run the pycocoZDemo.ipynb, there is an error as below, thanks.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-351a8514fb67> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
----> 2 from pycocotools.cocoz import ImageZ, AnnZ, COCOZ
      3 import numpy as np
      4 import skimage.io as io
      5 import matplotlib.pyplot as plt

H:\coco\cocoapi\PythonAPI\pycocotools\cocoz.py in <module>
     51 import json
     52 import time
---> 53 from . coco import COCO
     54 
     55 

H:\coco\cocoapi\PythonAPI\pycocotools\coco.py in <module>
     53 import copy
     54 import itertools
---> 55 from . import mask as maskUtils
     56 import os
     57 from collections import defaultdict

H:\coco\cocoapi\PythonAPI\pycocotools\mask.py in <module>
      1 __author__ = 'tsungyi'
      2 
----> 3 import pycocotools._mask as _mask
      4 
      5 # Interface for manipulating masks stored in RLE format.

ModuleNotFoundError: No module named 'pycocotools._mask'

**Comment by wangcn99** [comment]
have you slove this problem yet? i have the same problem with you

**Comment by xinetzone** [comment]
> This project needs to be compiled to support mask. For the compilation method, see “1 简介” of [COCO 数据集的使用](https://www.cnblogs.com/q735613050/p/8969452.html).
